server:
  port: 9102
spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: cards

logging:
  level:
    org.hibernate.SQL: debug      # 실행된 SQL 출력
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # SQL에 바인딩된 파라미터 값 출력
    