server:
  port: 9302

spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          ## locate all services registered in Eureka server (Actuator to get the list of services)
          # enabled: true
          lower-case-service-id: true
      httpclient:
        ## default 30000,
        connect-timeout: 1000
        ## default unlimited
        response-timeout: 2s
    stream:
      bindings:
        errorEvent-out-0:  # RabbitMQ로 장애 이벤트 전송
          destination: error-events
        errorEvent-in-0:   # Consumer가 메시지 받음
          destination: error-events
          group: mail-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"