# cards.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-hn
  namespace: group1-team7
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cards-hn
  template:
    metadata:
      labels:
        app: cards-hn
    spec:
      containers:
      - name: cards-hn
        image: k8s-vga-worker1:5000/group1-team7-cards-hn1:latest
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 9102
---
apiVersion: v1
kind: Service
metadata:
  name: cards-hn
  namespace: group1-team7
spec:
  selector:
    app: cards-hn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9102
      nodePort: 30733
  type: NodePort
