# gatewayserver.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-hn
  namespace: group1-team7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver-hn
  template:
    metadata:
      labels:
        app: gatewayserver-hn
    spec:
      containers:
      - name: gatewayserver-hn
        image: k8s-vga-worker1:5000/group1-team7-gatewayserver-hn:latest
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 9202
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver-hn
  namespace: group1-team7
spec:
  selector:
    app: gatewayserver-hn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9302
      nodePort: 30736
  type: NodePort
