server:
  port: 9103
spring:
  profiles:
    active: local
  application:
    name: loans

logging:
  level:
    org.hibernate.SQL: debug      # 실행된 SQL 출력
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # SQL에 바인딩된 파라미터 값 출력
    