spring:
  config:
    import: "optional:configserver:http://configserver-hn:80/"
  datasource:
      url: jdbc:mysql://team7-mysql:3306/team7_DB
      driverClassName: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-hn:80/eureka/ #Eureka Server 명시