server:
  port: 9200

spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ha-nakim/msa_config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          searchPaths: config-files
        native:  # 이렇게 설정해두면 git에 접속 불가 시 configserver/resorces/config 폴더안에 있는 properties를 참조함
          search-locations: "classpath:/config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
