server:
  port: 9310

spring:
  application:
    name: "message"
  cloud:
    function:
      # definition: email|sms; message;
      definition: email; message;
    stream:
      bindings:
        email-in-0:
          destination: hn-send-communication
          group: ${spring.application.name}
        message-in-0:
          destination: message-send
          group: ${spring.application.name}