# acounts.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-hn
  namespace: group1-team7
spec:
  replicas: 3
  selector:
    matchLabels:
      app: configserver-hn
  template:
    metadata:
      labels:
        app: configserver-hn
    spec:
      containers:
      - name: configserver-hn
        image: k8s-vga-worker1:5000/group1-team7-configserver-hn:latest
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-hn
  namespace: group1-team7
spec:
  selector:
    app: configserver-hn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9200
      nodePort: 30735
  type: NodePort
