build:
  version: "2.0"

spring:
  datasource:
      url: jdbc:mysql://192.168.100.221:30701/team7_DB
      driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    #function:
        #definition: updateCommunication
    stream:
      bindings:
        #updateCommunication-in-0:
          #destination: communication-sent
          #group: ${spring.application.name}
        #sendCommunication-out-0:
          #destination: send-communication
        sendMessage-out-0:
          destination: message-send
  rabbitmq:
    host: 192.168.100.221
    port: 30703
    username: admin
    password: admin
    connection-timeout: 10s
              
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/ #Eureka Server 명시
accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371