build:
  version: "1.0"

spring:
  datasource:
      url: jdbc:mysql://team7-mysql:3306/team7_DB
      driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    bus:
      enabled: true
    stream:
      bindings:
        sendCommunication-out-0:
          destination: hn-send-communication
        sendMessage-out-0:
          destination: message-send
  rabbitmq:
    host: rabbitmq-app
    port: 5672
    username: admin
    password: admin
    connection-timeout: 10s

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-hn:80/eureka/ #Eureka Server 명시

accounts:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384