build:
  version: "1.0"

spring:
  datasource:
      url: jdbc:mysql://team7-mysql:3306/team7_DB
      driverClassName: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-hn:80/eureka/ #Eureka Server 명시
      
cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@eazybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721