build:
  version: "1.0"

spring:
  datasource:
      url: jdbc:mysql://team7-mysql:3306/team7_DB
      driverClassName: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-hn:80/eureka/ #Eureka Server 명시
      
loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956