build:
  version: "2.0"

spring:
  datasource:
      url: jdbc:mysql://192.168.100.221:30701/team7_DB
      driverClassName: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/ #Eureka Server 명시

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Cyrano Marita - QA Lead"
    email: "cyrano@eazybank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467